# Generated by Django 4.1.7 on 2023-03-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_master_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_services',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.services'),
        ),
    ]
